# Generated by Django 4.2.30 on 2026-05-05 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qun', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='message',
            new_name='content',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
